### ISSUE TITLE
I suddenly get this Issue now worked fine last days

### ISSUE THREAD

**Issue by electrifying84** [Shishkebaboo/VodRecovery#11]
File "recovervod.py", line 856, in <module>
    run_script()
  File "recovervod.py", line 830, in run_script
    vod_filename = "{}_{}.mp4".format(parse_streamer_from_m3u8_link(vod_url), parse_vod_id_from_m3u8_link(vod_url))
  File "recovervod.py", line 201, in parse_streamer_from_m3u8_link
    streamer_name = url[indices[0] + 1:indices[-2]]

it happens when i want to download

Download M3U8 (.MP4 extension) and when i enter the link from twitchtracker

any help appreciated

**Comment by electrifying84** [comment]
it happens when i want to download 

6) Download M3U8 (.MP4 extension) and when i enter the link from twitchtracker

**Comment by Shishkebaboo** [comment]
@electrifying84 

Do you have the latest code? I pushed a fix for this yesterday.

**Comment by electrifying84** [comment]
@Shishkebaboo yeah im using Stable Release 1.0.0.9

i deleted whole folder and did all from scratch like pip install requirements 
pip upgrade and so on

still get the same error

**Comment by Shishkebaboo** [comment]
@electrifying84 You would need to clone main branch... 1.0.0.9 release is not considered latest code.

**Comment by electrifying84** [comment]
you mean git clone main branch? i done that yeah

**Comment by Shishkebaboo** [comment]
@electrifying84 Yes, not release 1.0.0.9... the actual main branch which would have additional changes past 1.0.0.9.

I just tried the application on the main branch I was able to start downloading a m3u8 and or a m3u8 file

**Comment by electrifying84** [comment]
@Shishkebaboo  

strange dont know why its not working on my side.. 
[doc.txt](https://github.com/Shishkebaboo/VodRecovery/files/10968524/doc.txt)

**Comment by Shishkebaboo** [comment]
@electrifying84 


Please choose an option: 1
Enter M3U8 Link: https://twitchtracker.com/trymacs/streams/40560773240


This is what I mentioned above... it needs a m3u8 link not a tracker link.

**Comment by electrifying84** [comment]
@Shishkebaboo 

sry for my dumbness

**Comment by Shishkebaboo** [comment]
Issue has been resolved. Closing issue.
